#!/bin/tcsh -f

  setenv nBinsMET   `grep nBinsMET   Binning.txt | awk '{print $2}'`
  setenv nBinsHT    `grep nBinsHT    Binning.txt | awk '{print $2}'`
  setenv nBinsBjets `grep nBinsBjets Binning.txt | awk '{print $2}'`
  setenv my_version `grep version    Binning.txt | awk '{print $2}'`
    
  # make workspace

  echo ... making workspace ...
  $ROOTSYS/bin/root -b -q make_ws_rootfile3b.c\(\"datfiles/Input-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets-v$my_version-withSyst.dat\",\"datfiles/T2tt-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets-v$my_version.dat\",700,0,\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",4,\"workspaces/ws-700-0-nB3.root\",\"null\",false,false,\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\",\"datfiles/DummySyst-met$nBinsMET-ht$nBinsHT-nB$nBinsBjets.dat\"\)

