#!/bin/tcsh -f

  setenv Var1 `grep Var1: Binning.txt | awk '{print $2}'`
  setenv Var2 `grep Var2: Binning.txt | awk '{print $2}'`

  setenv nBinsVar1  `grep nBinsVar1  Binning.txt | awk '{print $2}'`
  setenv nBinsVar2  `grep nBinsVar2  Binning.txt | awk '{print $2}'`
  setenv nBinsBjets `grep nBinsVar3  Binning.txt | awk '{print $2}'`
  setenv my_version `grep version    Binning.txt | awk '{print $2}'`

  if ( $Var1 == "MET/sqrt(HT)" ) then
    unsetenv Var1
    setenv Var1 MET_div_sqrtHT
  endif

  if ( $Var2 == "MET/sqrt(HT)" ) then
    unsetenv Var2
    setenv Var2 MET_div_sqrtHT
  endif

    
  # make workspace

  echo ... making workspace ...
  $ROOTSYS/bin/root -b -q make_ws_rootfile3b.c\(\"datfiles/Input-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets-v$my_version-withSyst.dat\",\"datfiles/TChiHH-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets-v$my_version.dat\",300,0,\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",4,\"rootfiles/ws-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets-v$my_version.root\",\"null\",false,false,\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\",\"datfiles/DummySyst-$Var1-$nBinsVar1-$Var2-$nBinsVar2-nB$nBinsBjets.dat\"\)

