/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBETAINVERSECDF
#define ROOBETAINVERSECDF

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBetaInverseCDF : public RooAbsReal {
public:
  RooBetaInverseCDF() {} ; 
  RooBetaInverseCDF(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
              Bool_t _useComplement=false);
  RooBetaInverseCDF(const RooBetaInverseCDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBetaInverseCDF(*this,newname); }
  inline virtual ~RooBetaInverseCDF() { }

protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy beta ;

  Bool_t useComplement ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBetaInverseCDF,1) // Your description goes here...
};
 
#endif
