/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooBetaInverseCDF.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "Math/Math.h"
#include "Math/QuantFuncMathCore.h"

ClassImp(RooBetaInverseCDF) 

 RooBetaInverseCDF::RooBetaInverseCDF(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _alpha,
                        RooAbsReal& _beta,
                        Bool_t _useComplement) :
   RooAbsReal(name,title), 
   x("x","x",this,_x),
   alpha("alpha","alpha",this,_alpha),
   beta("beta","beta",this,_beta),
   useComplement(_useComplement)
 { 
 } 


 RooBetaInverseCDF::RooBetaInverseCDF(const RooBetaInverseCDF& other, const char* name) :  
   RooAbsReal(other,name), 
   x("x",this,other.x),
   alpha("alpha",this,other.alpha),
   beta("beta",this,other.beta),
   useComplement(other.useComplement)
 { 
 } 



 Double_t RooBetaInverseCDF::evaluate() const 
 { 
   if(x<0 || x>1) return 0;
   if ( !useComplement ) {
      return ROOT::Math::beta_quantile(x,alpha,beta);
   } else {
      return ROOT::Math::beta_quantile_c(x,alpha,beta);
   }
 } 



