/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBETAPRIMEINVERSECDF
#define ROOBETAPRIMEINVERSECDF

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBetaPrimeInverseCDF : public RooAbsReal {
public:
  RooBetaPrimeInverseCDF() {} ; 
  RooBetaPrimeInverseCDF(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
              Bool_t _useComplement);
  RooBetaPrimeInverseCDF(const RooBetaPrimeInverseCDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBetaPrimeInverseCDF(*this,newname); }
  inline virtual ~RooBetaPrimeInverseCDF() { }

protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  
  Bool_t useComplement ;

  Double_t evaluate() const ;

private:

  ClassDef(RooBetaPrimeInverseCDF,1) // Your description goes here...
};
 
#endif
