/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCORRELATEDBETAGENERATORHELPER
#define ROOCORRELATEDBETAGENERATORHELPER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCorrelatedBetaGeneratorHelper : public RooAbsPdf {
public:
  RooCorrelatedBetaGeneratorHelper() {} ; 
  RooCorrelatedBetaGeneratorHelper(const char *name, const char *title,
	      RooAbsReal& _parameter,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta);
  RooCorrelatedBetaGeneratorHelper(const RooCorrelatedBetaGeneratorHelper& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCorrelatedBetaGeneratorHelper(*this,newname); }
  inline virtual ~RooCorrelatedBetaGeneratorHelper() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  void generateEvent(Int_t code);


protected:

  RooRealProxy parameter ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCorrelatedBetaGeneratorHelper,1) // Your description goes here...
};
 
#endif
