/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROONORMALFROMFLATPDF
#define ROONORMALFROMFLATPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooNormalFromFlatPdf : public RooAbsPdf {
public:
  RooNormalFromFlatPdf() {} ; 
  RooNormalFromFlatPdf(const char *name, const char *title,
	      RooAbsReal& _parameter);
  RooNormalFromFlatPdf(const RooNormalFromFlatPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooNormalFromFlatPdf(*this,newname); }
  inline virtual ~RooNormalFromFlatPdf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  Int_t getGenerator(const RooArgSet& directVars, RooArgSet &generateVars, Bool_t staticInitOK=kTRUE) const;
  void generateEvent(Int_t code);


protected:

  RooRealProxy parameter ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooNormalFromFlatPdf,1) // Your description goes here...
};
 
#endif
